# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: lint-and-test

on:
    pull_request:
        branches: ['main']

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
            - run: npm ci --force
            - run: npx eslint src

    test:
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
            - run: npm ci --force
            - run: npx vitest run
